---

- name: Install MySQL client for WP-CLI
  apt: name=mysql-client state=present update_cache=yes

- name: Is WP-CLI downloaded?
  stat: path="/usr/local/bin/wp"
  register: wpcli_is_downloaded

- name: Download WP-CLI
#  shell: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 0655
  when: wpcli_is_downloaded.stat.exists == False

- name: Make WP-CLI executable
  file:
    path: /usr/local/bin/wp
    mode: u=rwx,g=rx,o=rx
  when: wpcli_is_downloaded.stat.exists == False

- name: Download Wordpress to application dir
  get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/latest.tar.gz mode=0644

- name: Is WordPress downloaded?
  stat: path="{{app_dir}}/index.php"
  register: wordpress_is_downloaded

- name: Download WordPress
  shell: /usr/local/bin/wp core download --allow-root
  args:
    chdir: "{{app_dir}}"
  when: wordpress_is_downloaded.stat.exists == False

- name: Configure WordPress
  shell: /usr/local/bin/wp core config --allow-root
           --path="{{app_dir}}"
           --dbhost="{{db_address}}"
           --dbname="{{db_name}}"
           --dbuser="{{db_user}}"
           --dbpass="{{db_password}}"
  when: wordpress_is_downloaded.stat.exists == False

- name: Is WordPress installed?
  shell: /usr/local/bin/wp core is-installed --allow-root
  args:
    chdir: "{{app_dir}}/"
  register: wordpress_is_installed
  ignore_errors: True

- name: Install WordPress tables
  sudo: yes
  shell: /usr/local/bin/wp core install --allow-root
            --path="{{app_dir}}"
            --url="{{ wordpress_home_url }}"
            --title="{{ wordpress_site_title }}"
            --admin_user="{{ wordpress_admin_user }}"
            --admin_password="{{ wordpress_admin_user_pass }}"
            --admin_email="{{ wordpress_admin_email }}"
  when: wordpress_is_installed|failed
