---
- name: add the vhost
  template: src=wp_example.conf.j2 dest=/etc/nginx/sites-available/wp_example.conf
  notify:
      - Restart Nginx

- name: add hhvm configuration file
  template: src=hhvm.conf.j2 dest=/etc/nginx/hhvm.conf
  notify:
      - Restart Nginx

- name: enable the vhost on app only
  file: src=/etc/nginx/sites-available/wp_example.conf dest=/etc/nginx/sites-enabled/wp_example.conf state=link
  notify:
      - Restart Nginx

- name: Remove default debian index.html
  file: path=/var/www/html/index.nginx-debian.html state=absent

- name: Remove nginx default config
  file: path=/etc/nginx/sites-enabled/default state=absent
